[book]
title = "A guide to Telegram.Bot .NET library"
authors = ["Poulad Ashrafpour", "Aleksey Usatov", "Wizou", "karb0f0s", "Miha Zupan"]
description = "Comprehensive documentation to using the Telegram.Bot library and Bot API for building .NET bots for Telegram"
src = "src"
language = "en"

[output.html]
git-repository-url = "https://github.com/TelegramBots/book"
site-url = "/book/"
additional-css = ["theme/custom.css"]
admonitions = true
sidebar-header-nav = false

[output.html.fold]
enable = true
level = 1

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html.redirect]
"Migration-Guide-to-Version-21.x.html" = "/book/migrate/Version-21.x.html"
"3/files/index.html" = "/book/3/files.html"
"3/files/upload.html" = "/book/3/files.html"
"3/files/download.html" = "/book/3/files.html"
