[book]
authors = ["Poulad Ashrafpour", "Aleksey Usatov", "Wizou", "karb0f0s", "Miha Zupan"]
src = "src"
title = "A guide to Telegram.Bot library"
site-url = "https://telegrambots.github.io/book/"
language = "en"

[output.html]
git-repository-url = "https://github.com/TelegramBots/book"
site-url = "/book/"
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 1

[preprocessor.alerts]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html.redirect]
"Migration-Guide-to-Version-21.x.html" = "/book/migrate/Version-21.x.html"
"3/files/index.html" = "/book/3/files.html"
"3/files/upload.html" = "/book/3/files.html"
"3/files/download.html" = "/book/3/files.html"
